### ISSUE TITLE
Errors encountered in NG with latest

### ISSUE THREAD

**Issue by bornd37** [davecamp/srs.mod#1]
Really like the work you are doing on d3d11 driver. Thanks!

I have encountered some errors with the latest code from this repo. and the latest NG build. I have made some slight modifications and it seems to be running ok. Here is what I did for your analysis:

**Error #1:**
Compile Error: Duplicate identifier 'iunknown_' found in module 'pub.win32' and module 'srs.win32'.

Interface iunknown is defined in pub.win32 and looks exact except that Brucey has defined WParam and LParam, so here is what I did:

```
?bmxng

Rem
Extern"Win32"
Interface IUnknown_
	Method QueryInterface:Int(riid:Byte Ptr,ppIUnk:IUnknown_ Var)
	Method AddRef:Int()
	Method Release_:Int()
EndInterface
EndExtern
EndRem

Import pub.win32
?
```

Which leads to **Error #2:**
Compile Error: Unable to convert from Byte Ptr to WPARAM.

So I changed the Byte Ptr for wp and lp to WParam and LParam, respecively, in srs.mod/d3d11graphics.mod/d3d11graphics_ng.bmx, lines 38 and 367 (just WParam here).

With those changes the driver compiles and images are displayed, however I'm having some trouble with calls to DrawSubImageRect. Images drawn with this call appear briefly then disappear. Not sure if its related, but the d3d9 driver does not have this issue.

**Comment by davecamp** [comment]
Hiya
Thanks for using the driver.
My apologies as I'm not using the latest commits from the NG repo, I'll have to update.

Your fixes look good to me.
I'll investigate the DrawSubImageRect bug.

**Comment by bornd37** [comment]
Noticed I was in release mode. In Debug I'm getting a Windows Access Violation error. I'll post more on it when I have some details.

**Comment by bornd37** [comment]
Further testing shows the error occurs in the brl.d3d9max2d driver as well, so I don't think its an issue with your d3d11 driver. I've isolated it to an area in my code that has a file stream open. Weird, but I'll open the issue up with Brucey.

Thanks!
