### ISSUE TITLE
Doesn't compile in latest BlitzmaxNG

### ISSUE THREAD

**Issue by xlsior75** [davecamp/srs.mod#3]
No longer compiles using the latest Blitzmax NG:

Building x86 Release
[  8%] Processing:d3d11graphics_ng.bmx
Compile Error: Can't create instance of type TD3D11Graphics due to abstract Method TGraphics.Resize:Int(width:Int,height:Int).
[c:/code/BlitzmaxNG810/mod/srs.mod/d3d11graphics.mod/d3d11graphics_ng.bmx;119;0]
Build Error: failed to compile (-1) c:/code/BlitzmaxNG810/mod/srs.mod/d3d11graphics.mod/d3d11graphics_ng.bmx

**Comment by davecamp** [comment]
Are you using the very latest 'release' or the very latest commit?
I can build and run using latest 'release' 0.99.3.31

**Comment by xlsior75** [comment]
It's the current commits that won't compile D3D11graphics.
(All my other modules are OK, just that one broke)

**Comment by xlsior75** [comment]
Any ideas?

**Comment by davecamp** [comment]
I've just made a commit that should fix the problem.
I tested against v0.105.3.35

**Comment by xlsior75** [comment]
It looks like it is compiling now -- thanks!
