### ISSUE TITLE
SRS Compile error when BlitzMax NG

### ISSUE THREAD

**Issue by takis76** [davecamp/srs.mod#4]
This great module doesn't compiles in NG version of BlitzMax
When I am trying to compile the SRS module with BlitzMax NG in generates this error:

bmk makemods -a
The process goes well from 1% to 7% and then:
`
[  7%] Processing:d3d11graphics_ng.bmx
Compile Error: Can't create instance of type TD3D11Graphics due to abstract Meth
od TGraphics.GetSettings:Int(width:Int Var,height:Int Var,depth:Int Var,hertz:In
t Var,flags:Int Var,x:Int Var,y:Int Var).
[C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/srs.mod/d3d11graphics.mod/d3d11graph
ics_ng.bmx;119;0]
Build Error: failed to compile (-1) C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/s
rs.mod/d3d11graphics.mod/d3d11graphics_ng.bmx
`
Any ideas how to fix it?
Thank you :)

**Comment by GWRon** [comment]
Untested - but it reports that it needs "x:Int Var, y:Int Var" appended.

So replace that method with:
```BlitzMax
	Method GetSettings:Int( width:Int Var,height:Int Var,depth:Int Var,hertz:Int Var,flags:Int Var, x:Int Var, y:Int Var)
		width = _width
		height = _height
		depth = _depth
		hertz = _hertz
		flags = _flags
		x = 0
		y = 0
	EndMethod
```

This is needed if you use a brl.mod newer than 0.105 as then some stuff was added to allow positioning of the graphics window (for now only supported by SDL.mod)

**Comment by davecamp** [comment]
Hiya,

I will only support the latest release build that can be found at

[https://github.com/bmx-ng/bmx-ng/releases]

My main reason for this is that other, less advanced, users won't necessarily know how to build the compiler/modules from the latest commits, so if they were to download the latest release and this module is not in sync with that release then this module becomes broken... I feel it would give a bad vibe to the whole NG system for potential newer users of NG and this module.

When a new release pops out and if I'm slow in updating this module then feel free to raise another issue and I'll update it accordingly.

**Comment by davecamp** [comment]
In the meantime it's well worth modifying the **d3d11graphics_ng.bmx** file as @GWRon suggests above.

**Comment by GWRon** [comment]
Maybe the NG repos (and modules like this) should have two branches... Develop and master.
Also tags could be used

**Comment by takis76** [comment]
Hello,
I replaced the method with the method above and the error wasn't fixed.
It keeps to present the same error about:
Can't create instance of type TD3D11Graphics due to abstract Method TGraphics.Position:Int(x:Int,y:Int)

**Comment by GWRon** [comment]
Read what you wrote...think about it. Is it really the same error?
No it isn't

**Comment by takis76** [comment]
No now the error is in Method TGraphics.Position:Int(x.Int,y:Int) not in TGraphics.GetSettings
`
The error in detail:

[  7%] Processing:d3d11graphics_ng.bmx
Compile Error: Can't create instance of type TD3D11Graphics due to abstract Meth
od TGraphics.Position:Int(x:Int,y:Int).
[C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/srs.mod/d3d11graphics.mod/d3d11graph
ics_ng.bmx;119;0]
Build Error: failed to compile (-1) C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/s
rs.mod/d3d11graphics.mod/d3d11graphics_ng.bmx
`

**Comment by GWRon** [comment]
Create a so named function in the same file where you replaced the other one ...no content in the function needed.

Proceed the same with similar error messages in that file.

**Comment by takis76** [comment]
Something like this wasn't worked.

	Method Position:Int(x:Int Var, y:Int Var)
	EndMethod

**Comment by GWRon** [comment]
Error:
> due to abstract `Method TGraphics.Position:Int(x:Int,y:Int)`.

You:
>Something like this wasn't worked. `Method Position:Int(x:Int Var, y:Int Var)` 

spot the difference!
remove the difference (hint: 2x `Var`)
try again
be (hopefully) surprised 

---
Appending "var" is different as the effect is different:
https://en.wikibooks.org/wiki/BlitzMax/Modules/BASIC/BlitzMax_runtime#Var
You pass by reference - so you could do `x = otherVariable` and then the passed `x` refers to this variable (instead of just getting the _value_ assigned).

**Comment by takis76** [comment]
It passed this and continued with new error:
`
[  7%] Processing:d3d11graphics_ng.bmx
Compile Error: Can't create instance of type TD3D11GraphicsDriver due to abstract Method TGraphicsDriver.CreateGraphics:TGraphics(width:Int,height:Int,depth:Int,hertz:Int,flags:Int,x:Int,y:Int).
[C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/srs.mod/d3d11graphics.mod/d3d11graphics_ng.bmx;389;0]
Build Error: failed to compile (-1) C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/srs.mod/d3d11graphics.mod/d3d11graphics_ng.bmx
`

**Comment by takis76** [comment]
It seems I will need to append this x and y again.

**Comment by takis76** [comment]
I added this:

`
	Method CreateGraphics:TD3D11Graphics(width:Int, height:Int, depth:Int, hertz:Int, flags:Int, x:Int, y:Int)
		Return New TD3D11Graphics.Create(width, height, depth, hertz, flags)
	EndMethod
`
I wasn't set the x and y variables to 0. But it was passed and present a new error:

`
[  8%] Processing:common.bmx
Compile Error: Unable to find overload for creategraphics(Int,Int,Int,Int,Int).
Missing function parameter 'x'
[C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/srs.mod/d3d11max2d.mod/d3d11max2d_ng.bmx;762;0]
Build Error: failed to compile (-1) C:/Users/Takis/Desktop/BlitzMax/bmx-ng/mod/srs.mod/d3d11max2d.mod/d3d11max2d_ng.bmx
`

**Comment by GWRon** [comment]
There you need to append ,0,0

**Comment by takis76** [comment]
Ok the x and y variables still missing I added them too.

 Replaced this:
`
	Method CreateGraphics:TGraphics(width:Int, height:Int, depth:Int, hertz:Int, flags:Int)
		Local g:TD3D11Graphics = D3D11GraphicsDriver().CreateGraphics(width, height, depth, hertz, flags)
		If Not g Return Null
		Return TMax2DGraphics.Create(g, Self)
	EndMethod
`
With this:
`
	Method CreateGraphics:TGraphics(width:Int, height:Int, depth:Int, hertz:Int, flags:Int, x:Int, y:int)
		Local g:TD3D11Graphics = D3D11GraphicsDriver().CreateGraphics(width, height, depth, hertz, flags, x, y)
		If Not g Return Null
		Return TMax2DGraphics.Create(g,Self)
	EndMethod
`
Do I need to give initial values of 0 to x and y too?

**Comment by GWRon** [comment]
>Do I need to give initial values of 0 to x and y too?

No.
Defaults are 0 nonetheless ;-)
And it is a stub portion without any use than to satisfy the compiler and the framework definition of brl.graphics

**Comment by takis76** [comment]
It compiled and I tried to run some example.
In my project folder I have the file d3d11renderimage.bmx from Render2Texture and I have this error:

`
Compile Error: Unable to find overload for memcopy(Byte Ptr,Byte Ptr,Int). Argument #3 is "Int" but declaration is "size_t". 
Build Error: failed to compile (-1) in d3d11renderimage.bmx
`

The source code of the error is:

`
	Method ToPixmap:TPixmap(d3ddev:ID3D11Device, d3ddevcon:ID3D11DeviceContext)
		Local pDesc:D3D11_TEXTURE2D_DESC = New D3D11_TEXTURE2D_DESC
		_tex2D.GetDesc(pDesc)
		
		Local pixmap:TPixmap = CreatePixmap(pDesc.Width, pDesc.Height, PF_RGBA8888)

		' create a temp resource
		pDesc.Usage = D3D11_USAGE_STAGING
		pDesc.BindFlags = 0
		pDesc.CPUAccessFlags = D3D11_CPU_ACCESS_READ
		pDesc.MiscFlags = 0

		Local pStage:ID3D11Texture2D
		d3ddev.CreateTexture2D(pDesc, Null, pStage)
		d3ddevcon.CopyResource(pStage, _tex2D)

		Local map:D3D11_MAPPED_SUBRESOURCE = New D3D11_MAPPED_SUBRESOURCE
		d3ddevcon.Map(pStage, 0, D3D11_MAP_READ, 0, map)
			For Local y:Int = 0 Until pixmap.height
				Local dst:Byte Ptr = pixmap.pixels + y * pixmap.pitch
				Local src:Byte Ptr = map.pData + y * map.RowPitch
				MemCopy(dst, src, pixmap.pitch) '<= THE PROBLEM IS HERE
			Next
		d3ddevcon.UnMap(pStage, 0)
		
		pStage.Release_()
		
		Return pixmap
	EndMethod
`

**Comment by GWRon** [comment]
Wrap the 3rd argument in
size_t(...)

**Comment by takis76** [comment]
Like this one?
MemCopy(dst, src, size_t(pixmap.pitch))

And from the Render2texture one of the files with name: d3d9renderimage.bmx there is another one Method with name 

`
	Method OnDeviceReset(d3ddev:IDirect3DDevice9)
		Local width:Int = _persistpixmap.width
		Local height:Int = _persistpixmap.height

		d3ddev.CreateTexture(width, height, 1, D3DUSAGE_RENDERTARGET, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, _texture, Null)
		If _texture _texture.GetSurfaceLevel(0, _surface)

		' use a staging surface to copy the pixmap into
		Local stage:IDirect3DSurface9
		d3ddev.CreateOffscreenPlainSurface(width, height, D3DFMT_A8R8G8B8, D3DPOOL_SYSTEMMEM, stage, Null)

		Local lockedrect:D3DLOCKED_RECT = New D3DLOCKED_RECT
		stage.LockRect(lockedrect, Null, 0)

		' copy the pixel data across
		For Local y:Int = 0 Until _persistpixmap.height
			Local srcptr:Byte Ptr = _persistpixmap.pixels + y * _persistpixmap.pitch
			Local dstptr:Byte Ptr = lockedrect.pBits + y * lockedrect.Pitch
			MemCopy dstptr, srcptr, _persistpixmap.width * 4 '<THE PROBLEM IS HERE
		Next
		stage.UnlockRect()

		' copy from the staging surface to the render surface
		d3ddev.UpdateSurface(stage, Null, _surface, Null)

		' cleanup
		stage.release_
		_persistpixmap = Null
	EndMethod
`
I changed to:
MemCopy dstptr, srcptr, size_t(_persistpixmap.width) * 4
Or needs to be changed to:
MemCopy dstptr, srcptr, size_t(_persistpixmap.width * 4)

**Comment by GWRon** [comment]
The second one. The whole argument needs to be passed as size_t (hence this casting requirement).

**Comment by takis76** [comment]
There is a new error in file: d3d9renderimage.bmx

Compile Error: Unable to find overload for getviewport(D3DVIEWPORT9). Argument #1 is "D3DVIEWPORT9" but declaration is "Byte Ptr". 
Build Error: failed to compile (-1) E:/Dlb2/d3d9renderimage.bmx

In method: Method Init(d3ddev:IDirect3DDevice9, UseImageFiltering:Int)

`
	Method Init(d3ddev:IDirect3DDevice9, UseImageFiltering:Int)
		_d3ddev = d3ddev
		_d3ddev.AddRef()

		frames = New TD3D9RenderImageFrame[1]
		frames[0] = New TD3D9RenderImageFrame.CreateRenderTarget(d3ddev, width, height)
		If UseImageFiltering
			TD3D9RenderImageFrame(frames[0])._magfilter=D3DTFG_LINEAR
			TD3D9RenderImageFrame(frames[0])._minfilter=D3DTFG_LINEAR
			TD3D9RenderImageFrame(frames[0])._mipfilter=D3DTFG_LINEAR
		Else
			TD3D9RenderImageFrame(frames[0])._magfilter=D3DTFG_POINT
			TD3D9RenderImageFrame(frames[0])._minfilter=D3DTFG_POINT
			TD3D9RenderImageFrame(frames[0])._mipfilter=D3DTFG_POINT
		EndIf


		'  clear the new render target surface
		Local prevsurf:IDirect3DSurface9
		Local prevmatrix:Float[16]
		Local prevviewport:D3DVIEWPORT9 = New D3DVIEWPORT9
		' get previous
		d3ddev.GetRenderTarget(0, prevsurf)
		d3ddev.GetTransform(D3DTS_PROJECTION, prevmatrix)
		d3ddev.GetViewport(prevviewport) '<= THE PROBLEM IS HERE

		' set and clear
		d3ddev.SetRenderTarget(0, TD3D9RenderImageFrame(frames[0])._surface)
		d3ddev.SetTransform(D3DTS_PROJECTION, _matrix)
		d3ddev.Clear(0, Null, D3DCLEAR_TARGET, 0, 0.0, 0) 

		' reset to previous
		_d3ddev.SetRenderTarget(0, prevsurf)
		_d3ddev.SetTransform(D3DTS_PROJECTION, prevmatrix)
		_d3ddev.SetViewport(prevviewport)

		' cleanup
		prevsurf.release_
	EndMethod
`
The problem is in the line: d3ddev.GetViewport(prevviewport)

**Comment by GWRon** [comment]
Dunno about this, maybe @Davecamp can jump in?

**Comment by takis76** [comment]
I will wait for Devecamp to log in and see this post.

**Comment by davecamp** [comment]
@takis76 
Did you read the note at the bottom of the Render2Texture repository front page?

**Comment by davecamp** [comment]
I'll put some more work into getting the Render2Texture code working with the DirectX drivers in NG.

**Comment by takis76** [comment]
> Did you read the note at the bottom of the Render2Texture repository front page?
Yes I have replaced the d3d9graphics.bmx in the brl/dxgraphics.mod and I have recompiled the brl module again.
The problem appears in other files which are from Render2Texture source code which you place them in the project directory.

> I'll put some more work into getting the Render2Texture code working with the DirectX drivers in NG.
Nice I will wait. It will be nice if all of these problems will be corrected and people will not need to do whole of this manual editing and not understanding and what fix will need to do and wait for other people to answer.

**Comment by takis76** [comment]
From the syntaxbomb forums the user Derron said if I will use older version of brl (BlitzMax) maybe all of these errors will not present. I amcurrently using the version BlitzMax_win32_0.105.3.35. Maybe the previous one BlitzMax_win32_0.99.3.31 will not have errors. I don't know I haven't tested it. I thought the most recent would be better. But if you fix the current one will be very nice.
Thank you :)

**Comment by GWRon** [comment]
Dunno how often to say... Derron is me. And davecamp is Col.

I said older version of brl.mod ...so the one of .105. not a newer one

**Comment by takis76** [comment]
If you are Derron its nice. This answer was for Davecamp. Yes I know the version .105 is the most recent and I said about the version  .99 or I understood. Maybe it will work. You said if I will use earlier version and replace the brl module only maybe it will work.
You are using different nicknames in different forums and I believe I am talking with a different people :)

**Comment by GWRon** [comment]
@davecamp said he won't update for bleeding edge stuff...so he tries to make stuff work with the latest official BlitzMax NG release. v0.105 is the latest and for this the modules should work. If they are erroring out then one should file an issue / bug report.

But you seemed to have updated brl.mod and pub.mod (as I suggested because of other errors you had). With updated brl.mod stuff in srs.mod needs to get updated (which @davecamp neglected...see first paragraph).

**Comment by takis76** [comment]
The first paragraph was said about the note from at the bottom of the Render2Texture repository front page which explained about replacing the file d3d9graphics.bmx in brl which I have alread done that.

**Comment by davecamp** [comment]
@takis76 
1. Are you using srs.mod with BlitzmaxNG?
2. Are you using srs.mod with BRLs Blitzmax?
3. Are you using Render2Texture with BlitzmaxNG?
4. Are you using Render2Texture with BRLs Blitzmax?
5. Maybe it would be better to use the Render2Texture github repo for problems with that code.

@GWRon @takis76 
I'll create a dev branch that will be compatible with the latest NG

**Comment by davecamp** [comment]
[edit] Just for this repo only...

There's now a dev branch that will work with the latest NG. The master branch will only be compatible with release versions of NG.

Hope it helps!

**Comment by takis76** [comment]
@Devcamp
1. I am using the srs module in BlitzMax NG which I downloaded it from here: https://blitzmax.org/downloads
2. I am using the srs.mod which I have downloaded it from here: https://github.com/davecamp/srs.mod
3. I am using the Render2Texture in BlitzMax NG which I downloaded it from here: https://github.com/davecamp/Render2Texture
4. The Render2Texture is working in non NG version of brl and BlitzMax which I am already have installed it in the BlitzMax 1.52
5. All of these links are GitHub links. Are there any other Srs and Render2Texture GitHub links? I believe I am already using the GitHub versions and I thought they were fixed already.

> I'll create a dev branch that will be compatible with the latest NG

If the development branch will fix all of these and everything will work out of the box, it will be very very nice. I thank you very very much :)
(A detailed installation instruction document will be very appreciated).

**Comment by davecamp** [comment]
1. That's great - that's the latest supported version for the master branch of this repo
2. That's the correct repo for srs.mod
3. That's also the correct repo for Render2Texture
4. Render2Texture was originally made with 'non NG' in mind so it should always work with 'non NG' without issues. @GWRon requested for SDL support for NG which means only SDL graphics drivers will work when Render2Texture is used with NG - I'll work more of this in order to get the Max2D DirectX drivers (D3D9 and D3D11) working too.
5. No you have all of the correct links 8^)

Have fun!

**Comment by GWRon** [comment]
Yeah, think getting to work the "NG brl.graphics" (so d3d9 and gl + srs.mod's dx11) would be _really_ cool as you then can just use it - without having t think about what renderer is used.

Once it just "works" I would ask to make it a default module ("brl.render2texture") as rendering to textures should be one of the major things people can do improving the render performance in max2D (especially with a lot of text or tiny decoration elements).

Maybe you want to add a licence too - like zlib/libpng (very permissive but at least mentioning you as author). Sample: https://github.com/bmx-ng/brl.mod/blob/master/base64.mod/base64.bmx
