### ISSUE TITLE
circular import in dxgi_ng.bmx

### ISSUE THREAD

**Issue by braxtonrivers** [davecamp/srs.mod#7]
dxgi.mod/dxgi_ng.bmx

`Import "dxgi.bmx"`

creates a circular import as it is imported from dxgi.bmx

**Comment by davecamp** [comment]
I'll get this fixed up in the next days

**Comment by davecamp** [comment]
I've pushed a complete new version to the 'dev' branch which should also be faster than the original ng version too.
