### ISSUE TITLE
Cannot create shader input layout

### ISSUE THREAD

**Issue by braxtonrivers** [davecamp/srs.mod#9]
With the circular import commented out, and after adding back in the missing include "DeviceModeSettings.c" the example results in the following error on Windows 11:

Cannot create shader input layout

```
Superstrict

Framework srs.d3d11max2d
SetGraphicsDriver D3D11Max2DDriver()
Local driver$ = GetGraphicsDriver().ToString()

Graphics 800, 600

While Not KeyDown(KEY_ESCAPE)
  DrawText driver, 0, 0
  Flip
Wend
```

**Comment by davecamp** [comment]
I'll get this fixed up in the next days

**Comment by braxtonrivers** [comment]
thank you, and no worries i appreciate your module

**Comment by davecamp** [comment]
Hiya,
I've pushed a complete new version to the 'dev' branch if you wanted to give that a go before I merge it into the main branch.
If should be faster than the original ng version.

**Comment by braxtonrivers** [comment]
Hi dave, I installed the 'dev' branch and it appears to be working, and it definitely does appear to be faster too, which is awesome, thank you!
